@url_dev =  http://localhost:8080/api/v1
### GET ALL POST
GET {{url_dev}}/posts

### GET A SINGLE POST
GET {{url_dev}}/posts/1

### CREARE A NEW POST
POST {{url_dev}}/posts
Content-Type: application/json

{
    "title": "title 7",
    "content": "content 7"
}

### UPDATE A POST

PATCH {{url_dev}}/posts/5
Content-Type: application/json

{
    "title": "title 5 update",
    "content": "content 5 update"
}

### DELETE A POST
DELETE {{url_dev}}/posts/6

